<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugs.eclipse.org/bugs/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.7"
          urlbase="https://bugs.eclipse.org/bugs/"
          
          maintainer="webmaster@eclipse.org"
>

    <bug>
          <bug_id>411708</bug_id>
          
          <creation_ts>2013-06-26 12:58:00 -0400</creation_ts>
          <short_desc>NPE When comparing with no remote</short_desc>
          <delta_ts>2013-07-03 19:46:35 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>14</classification_id>
          <classification>Mylyn</classification>
          <product>Mylyn Reviews</product>
          <component>Gerrit Connector</component>
          <version>unspecified</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>2.0.1</target_milestone>
          
          <blocked>411652</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Miles Parker">milesparker</reporter>
          <assigned_to name="Miles Parker">milesparker</assigned_to>
          <cc>sam.davis</cc>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>2277485</commentid>
    <comment_count>0</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-26 12:58:01 -0400</bug_when>
    <thetext>If you attempt to compare with another patch set after disconnecting to an existing remote, you get an NPE.

java.lang.NullPointerException
	at org.eclipse.mylyn.internal.gerrit.core.remote.PatchSetContentRemoteFactory.pull(PatchSetContentRemoteFactory.java:66)
	at org.eclipse.mylyn.internal.gerrit.core.remote.PatchSetContentCompareRemoteFactory.pull(PatchSetContentCompareRemoteFactory.java:38)
	at org.eclipse.mylyn.internal.gerrit.core.remote.PatchSetContentCompareRemoteFactory.pull(PatchSetContentCompareRemoteFactory.java:1)
	at org.eclipse.mylyn.reviews.core.spi.remote.emf.RemoteEmfConsumer.pull(RemoteEmfConsumer.java:164)
	at org.eclipse.mylyn.reviews.core.spi.remote.JobRemoteService$1.run(JobRemoteService.java:60)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2277499</commentid>
    <comment_count>1</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-26 13:26:26 -0400</bug_when>
    <thetext>This issue was introduced when solving the issue of how to deal with patch sets when only one commit was not available. The current code now absorbs and logs the exception but that doesn&apos;t work for some cases where the issue was caused by no connectivity.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2277507</commentid>
    <comment_count>2</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-06-26 13:41:05 -0400</bug_when>
    <thetext>https://git.eclipse.org/r/14077 (Please ignore spurious test exception.)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2280462</commentid>
    <comment_count>3</comment_count>
    <who name="Miles Parker">milesparker</who>
    <bug_when>2013-07-03 19:46:35 -0400</bug_when>
    <thetext>Merged https://git.eclipse.org/r/14077.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>